---
jobs:

- name: run-tests
  plan:
    - in_parallel:
      - get: cg-django-uaa-pr
        trigger: true
      - get: general-task
    - put: cg-django-uaa-pr
      params:
        path: cg-django-uaa-pr
        status: pending
    - task: run-tests
      image: general-task
      file: cg-django-uaa-pr/ci/run-tests.yml
      on_failure:
        put: cg-django-uaa-pr
        params:
          path: cg-django-uaa-pr
          status: failure
      on_success:
        put: cg-django-uaa-pr
        params:
          path: cg-django-uaa-pr
          status: success

- name: set-self
  plan:
    - get: cg-django-uaa-repo
      trigger: true
    - set_pipeline: self
      file: cg-django-uaa-repo/ci/pipeline.yml

- name: create-release
  plan:
    - in_parallel:
        - get: cg-django-uaa-repo-tag
          trigger: true
        - get: general-task
    - task: prepare-release
      image: general-task
      file: cg-django-uaa-repo-tag/ci/prepare-release.yml
    - task: test-release
      image: general-task
      file: cg-django-uaa-repo-tag/ci/test-release.yml
    - put: cg-django-uaa-release
      params:
        name: cg-django-uaa-repo-tag/tag
        tag: cg-django-uaa-repo-tag/tag
        generate_release_notes: true
        globs:
          - cg-django-uaa-repo-tag/dist/cg_django_uaa*
  on_failure:
    put: slack
    params:
        text: |
            :x: FAILED to release cg-django-uaa
            <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: ((slack-failure-channel))
        username: ((slack-username))
        icon_url: ((slack-icon-url))
  on_success:
    put: slack
    params:
        text: |
            :white_check_mark: Successfully released cg-django-uaa
            <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: ((slack-success-channel))
        username: ((slack-username))
        icon_url: ((slack-icon-url))

resources:
- name: cg-django-uaa-pr
  type: pull-request
  check_every: 1m
  source:
    repository: cloud-gov/cg-django-uaa
    access_token: ((status-access-token))
    disable_forks: true

# this resource is this repo
- name: cg-django-uaa-repo
  type: git
  source:
    uri: https://github.com/cloud-gov/cg-django-uaa.git
    branch: main
    commit_verification_keys: ((cloud-gov-pgp-keys))

# this resource is this repo
# NOTE: we only execute on tag changes not commits, see tag_regex
- name: cg-django-uaa-repo-tag
  type: git
  source:
    uri: https://github.com/cloud-gov/cg-django-uaa.git
    # only run on new tags matching pattern like: v0.1.5
    tag_regex: '^v([0-9]+\.){0,2}(\*|[0-9]+)$'
    commit_verification_keys: ((cloud-gov-pgp-keys))

# This resource for posting to slack
- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))

# Resource for creating a new release
- name: cg-django-uaa-release
  type: github-release
  source:
    owner: cloud-gov
    repository: cg-django-uaa
    access_token: ((cg-ci-bot-ghtoken))

- name: general-task
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: general-task
    aws_region: us-gov-west-1
    tag: latest

resource_types:
- name: registry-image
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: registry-image-resource
    aws_region: us-gov-west-1
    tag: latest

- name: slack-notification
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: slack-notification-resource
    aws_region: us-gov-west-1
    tag: latest

- name: git
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: git-resource
    aws_region: us-gov-west-1
    tag: latest

- name: pull-request
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: github-pr-resource
    aws_region: us-gov-west-1
    tag: latest

- name: github-release
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: github-release-resource
    aws_region: us-gov-west-1
    tag: latest
